services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ../packages/frontend:/app/packages/frontend
      - ../packages/common:/app/packages/common
      - frontend_node_modules:/app/packages/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ../packages/backend:/app/packages/backend
      - ../packages/common:/app/packages/common
      - backend_node_modules:/app/packages/backend/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=appdb
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  frontend_node_modules:
  backend_node_modules:
  mysql_data: